ALTER TABLE especialidade
ADD COLUMN url_imagem varchar(255);

INSERT INTO especialidade(titulo,descricao,url_imagem) VALUES
('Cardiologia','A cardiologia é a especialidade médica que se concentra no diagnóstico e tratamento de doenças do coração e do sistema circulatório. Cardiologistas lidam com condições como doença coronariana, insuficiência cardíaca, arritmias e hipertensão.','https://ariumsaude.com.br/wp-content/uploads/2021/04/Cardiologia_iStock-530199842.jpg'),
('Dermatologia','Dermatologistas se especializam na saúde da pele, cabelos e unhas. Eles diagnosticam e tratam uma variedade de condições dermatológicas, incluindo acne, eczema, psoríase e câncer de pele.','https://i0.wp.com/dranidialima.com.br/wp-content/uploads/2020/11/dermatologia.jpg?fit=1000%2C861&ssl=1'),
('Ortopedia','A ortopedia trata do sistema musculoesquelético, incluindo ossos, articulações, ligamentos, tendões e músculos. Ortopedistas lidam com fraturas, lesões esportivas, doenças degenerativas e deformidades ósseas.','https://www.hcor.com.br/wp-content/uploads/2017/01/ortopedia-pe.jpg'),
('Neurologia','Neurologistas se dedicam ao estudo do sistema nervoso, diagnosticando e tratando condições neurológicas como enxaquecas, epilepsia, doença de Parkinson e esclerose múltipla.','https://www.santaritaclinicamedica.com.br/upload/conteudo/24/2002261230095343.jpg'),
('Pediatria', 'Os pediatras são médicos que cuidam da saúde de crianças desde o nascimento até a adolescência. Eles tratam uma variedade de condições pediátricas e monitoram o desenvolvimento infantil.','https://www.institutovillamil.com.br/wp-content/uploads/2022/06/pediatriaintegrativaVillamil.png'),
('Ginecologia/Obstetrícia','Ginecologistas se especializam na saúde da mulher, enquanto obstetras se concentram na gravidez e parto. Juntos, eles abordam questões ginecológicas, como saúde reprodutiva, gravidez e parto.','https://institucional-cms.medprev.app/storage/medprev-institucional-cms-prdqual_a_diferenca_entre_ginecologista_e_obstetra_f3521dbf65.jpeg'),
('Psiquiatria','Psiquiatras tratam distúrbios mentais, emocionais e comportamentais. Eles podem utilizar terapia, medicação ou uma combinação de abordagens para ajudar pacientes com condições como depressão, ansiedade e transtorno bipolar.','https://clinicaqualivita.com.br/wp-content/uploads/2021/05/Psiquiatria.png'),
('Endocrinologia','Endocrinologistas lidam com distúrbios hormonais, abrangendo glândulas endócrinas como a tireoide, pâncreas e glândulas suprarrenais. Diabetes, distúrbios da tireoide e desequilíbrios hormonais são exemplos de condições tratadas por endocrinologistas.','https://medcorsorocaba.com.br/wp-content/uploads/2019/01/medcor_endocrinologia-800x447.jpg'),
('Oftalmologia','Oftalmologistas são médicos especializados em cuidar dos olhos e da visão. Eles diagnosticam e tratam condições oculares, realizam cirurgias oculares, prescrevem óculos e lentes de contato, entre outras atividades relacionadas à saúde ocular.','https://blog.eyetec.com.br/wp-content/uploads/2021/08/inteligencia_artificial_oftalmologia_1-1080x555-1.jpg'),
('Urologia','Urologistas tratam do sistema urinário em ambos os sexos e do sistema reprodutivo masculino. Isso inclui condições como infecções do trato urinário, câncer de próstata e disfunção erétil.','https://medcorsorocaba.com.br/wp-content/uploads/2019/01/medcor_urologia-.jpg');

